spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
eventuatelocal:
  kafka:
    bootstrap:
      servers: http://192.168.94.128:9092
  zookeeper:
    connection:
      string: http://192.168.94.128:2181
server:
  port: 9001